---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./emberstack.yaml
  - ./external-dns.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-at-home.yaml
  - ./k8s-at-home-charts.yaml
  - ./k8s-gateway.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./stakater.yaml
  - ./weaveworks-kured.yaml
  - ./traefik.yaml
  - ./rook-ceph-charts.yaml
  - ./truecharts.yaml
  - ./nfs.yaml
  - ./nfs-csi.yaml
  - ./kasten.yaml
  - ./longhorn.yaml
  - ./ubuntu.yaml
  - ./bjw-s-charts.yaml
  - ./prometheus-community.yaml
  - ./grafana.yaml
  - ./portainer.yaml
  - ./vmware-tanzu-charts.yaml
  - ./goldilocks.yaml
  - ./kyverno.yaml
  - ./kubernetes-dashboard-charts.yaml
  - ./rancher-latest-charts.yaml
  - ./cloudnative-pg.yaml
  - ./dandydeveloper-charts.yaml
  - ./descheduler.yaml
  - ./influxdata.yaml
  - ./vector-charts.yaml
  - ./deliveryhero-charts.yaml
  - ./savepointsam-charts.yaml
  - ./pihole-charts.yaml
  - ./runix.yaml
  - ./goauthentik-charts.yaml
  - ./gitea.yaml
  - ./netdata.yaml
  - ./tubearchivist.yaml
